on:
  push:
    branches:
      - main

name: Build and deploy the props components to the production environment

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          project-id: ${{secrets.PROJECT_ID}}
          another-secret: ${{secrets.ANOTHER_SECRET}}
      - name: Echo SDK
        run: ECHO $project-id $another-secret $ANOTHER_SECRET
